package inspector.jmondb.model;

import javax.persistence.*;
import java.util.HashMap;
import java.util.Map;

@Entity
@Table(name="project")
public class Project {

	/** read-only iMonDB primary key; generated by JPA */
	@Id
	@Column(name="id", nullable=false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private long id;
	/** the project description */
	@Column(name="description", length=255)
	private String description;
	/** the label identifying the project */
	@Column(name="label", nullable=false, unique=true, length=20)
	private String label;
	/** the project title */
	@Column(name="title", nullable=false, length=100)
	private String title;

	//TODO
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="fromProject")
	@MapKey(name="id")
	private Map<Long, Run> hasRuns;

	/**
	 * Creates a Project with the specified label and title.
	 *
	 * The id is automatically determined by the database as primary key.
	 *
	 * @param label  The label identifying the project
	 * @param title  The project title
	 */
	public Project(String label, String title) {
		this.label = label;
		this.title = title;

		hasRuns = new HashMap<>();
	}

	/**
	 * Creates a Project with the specified label, title and description.
	 *
	 *  The primary key is automatically determined by the database.
	 *
	 * @param label  The label identifying the project
	 * @param title  The project title
	 * @param description  The project description
	 */
	public Project(String label, String title, String description) {
		this(label, title);
		this.description = description;
	}

	public long getId() {
		return id;
	}

	/* package private: read-only key to be set by the JPA implementation */
	void setId(long id) {
		this.id = id;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) return true;
		if(o == null || getClass() != o.getClass()) return false;

		Project that = (Project) o;

		if(id != that.id) return false;
		if(description != null ? !description.equals(that.description) : that.description != null) return false;
		if(label != null ? !label.equals(that.label) : that.label != null) return false;
		if(title != null ? !title.equals(that.title) : that.title != null) return false;

		return true;
	}

	@Override
	public int hashCode() {
		int result = (int) (id ^ (id >>> 32));
		result = 31 * result + (description != null ? description.hashCode() : 0);
		result = 31 * result + (label != null ? label.hashCode() : 0);
		result = 31 * result + (title != null ? title.hashCode() : 0);
		return result;
	}
}
