package inspector.imondb.collector.view.gui.metadata;

/*
 * #%L
 * iMonDB Collector
 * %%
 * Copyright (C) 2014 - 2015 InSPECtor
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import inspector.imondb.collector.controller.listeners.ConfigurationChangeListener;
import inspector.imondb.collector.model.MetadataMap;
import inspector.imondb.collector.view.gui.instrument.RegexMapTestPanel;

import javax.swing.*;
import java.awt.*;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import java.util.Observable;

public class MetadataPanel extends Observable {

    private JPanel panel;

    private JButton buttonAdd;
    private JButton buttonTest;

    private JScrollPane scrollPaneMetadata;
    private JPanel panelMetadata;
    private Map<MetadataMap, MetadataOverviewPanel> metadataMaps;

    public MetadataPanel() {
        metadataMaps = new HashMap<>();

        $$$setupUI$$$();
        buttonAdd.addActionListener(e -> {
            MetadataCreatePanel metadataCreatePanel = new MetadataCreatePanel();
            int result = JOptionPane.showConfirmDialog(Frame.getFrames()[0], metadataCreatePanel.getPanel(),
                    "Add metadata", JOptionPane.OK_CANCEL_OPTION);
            if(result == JOptionPane.OK_OPTION) {
                MetadataMap metadataMap = metadataCreatePanel.getMetadataMap();
                if(metadataMap.isValid() && !metadataMaps.containsKey(metadataMap)) {
                    addMetadata(metadataMap);
                    panelMetadata.revalidate();
                    panelMetadata.repaint();
                    scrollPaneMetadata.revalidate();
                } else {
                    JOptionPane.showMessageDialog(Frame.getFrames()[0], "<html>Invalid metadata configuration.<br><br>Please try to add the metadata again.<br>" +
                                    "Make sure that all fields are correctly set,<br>and that no other metadata with the<br>same key-value combination already exists.</html>",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        buttonTest.addActionListener(e -> {
            RegexMapTestPanel regexMapTestPanel = new RegexMapTestPanel(getMetadata());
            JOptionPane.showMessageDialog(panel, regexMapTestPanel.getPanel(), "Test metadata configuration", JOptionPane.PLAIN_MESSAGE);
        });
    }

    public MetadataPanel(Collection<MetadataMap> metadata) {
        this();

        metadata.forEach(this::addMetadata);
    }

    private void createUIComponents() {
        panelMetadata = new JPanel();
        panelMetadata.setLayout(new BoxLayout(panelMetadata, BoxLayout.PAGE_AXIS));
    }

    public JPanel getPanel() {
        return panel;
    }

    private void addMetadata(MetadataMap metadataMap) {
        MetadataOverviewPanel metadataOverviewPanel = new MetadataOverviewPanel(this, metadataMap);
        metadataOverviewPanel.getPanel().setAlignmentX(Component.LEFT_ALIGNMENT);
        panelMetadata.add(metadataOverviewPanel.getPanel());

        metadataMaps.put(metadataMap, metadataOverviewPanel);

        setChanged();
        notifyObservers(metadataMap);
    }

    void removeMetadata(MetadataMap metadataMap) {
        panelMetadata.remove(metadataMaps.get(metadataMap).getPanel());
        metadataMaps.remove(metadataMap);

        setChanged();
        notifyObservers();
    }

    void editMetadata(MetadataMap metadataMap) {
        MetadataOverviewPanel metadataOverviewPanel = metadataMaps.remove(metadataMap);
        metadataMaps.put(metadataMap, metadataOverviewPanel);

        setChanged();
        notifyObservers(metadataMap);
    }

    public Collection<MetadataMap> getMetadata() {
        return metadataMaps.keySet();
    }

    public void addConfigurationChangeListener(ConfigurationChangeListener listener) {
        addObserver(listener);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setMinimumSize(new Dimension(500, 250));
        panel1.setPreferredSize(new Dimension(500, 250));
        panel.add(panel1);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null));
        final JLabel label1 = new JLabel();
        label1.setText("Metadata");
        label1.setDisplayedMnemonic('M');
        label1.setDisplayedMnemonicIndex(0);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.TRAILING, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel2, gbc);
        buttonAdd = new JButton();
        buttonAdd.setHorizontalTextPosition(0);
        buttonAdd.setIcon(new ImageIcon(getClass().getResource("/images/add.png")));
        buttonAdd.setMaximumSize(new Dimension(29, 29));
        buttonAdd.setMinimumSize(new Dimension(29, 29));
        buttonAdd.setPreferredSize(new Dimension(29, 29));
        buttonAdd.setText("");
        buttonAdd.setToolTipText("Add new metadata");
        panel2.add(buttonAdd);
        buttonTest = new JButton();
        buttonTest.setHorizontalTextPosition(0);
        buttonTest.setIcon(new ImageIcon(getClass().getResource("/images/search.png")));
        buttonTest.setMaximumSize(new Dimension(29, 29));
        buttonTest.setMinimumSize(new Dimension(29, 29));
        buttonTest.setPreferredSize(new Dimension(29, 29));
        buttonTest.setText("");
        buttonTest.setToolTipText("Test the metadata regex configuration");
        panel2.add(buttonTest);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel3.setMinimumSize(new Dimension(405, 200));
        panel3.setPreferredSize(new Dimension(405, 200));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(panel3, gbc);
        scrollPaneMetadata = new JScrollPane();
        scrollPaneMetadata.setHorizontalScrollBarPolicy(31);
        panel3.add(scrollPaneMetadata, BorderLayout.CENTER);
        scrollPaneMetadata.setViewportView(panelMetadata);
        label1.setLabelFor(scrollPaneMetadata);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }
}
