package inspector.jmondb.model;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.persistence.*;

/**
 * A {code CV} represents a controlled vocabulary which contains a formal definition for some {@link Property}s.
 */
@Entity
@Access(AccessType.FIELD)
@Table(name="imon_cv")
public class CV {

	@Transient
	private static final Logger logger = LogManager.getLogger(CV.class);

	/** read-only iMonDB primary key; generated by JPA */
	@Id
	@Column(name="id", nullable=false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;

	/** the label identifying the controlled vocabulary */
	@Column(name="label", nullable=false, unique=true, length=20)
	private String label;
	/** the full name of the controlled vocabulary */
	@Column(name="name", nullable=false, length=200)
	private String name;
	/** the uri specifying the location of the controlled vocabulary */
	@Column(name="uri", nullable=false, length=200)
	private String uri;
	/** the version number of the controlled vocabulary */
	@Column(name="version", length=20)
	private String version;

	/**
	 * Default constructor required by JPA.
	 * Protected access modification enforces class immutability.
	 */
	protected CV() {

	}

	/**
	 * Creates a {@code CV} representing a controlled vocabulary.
	 *
	 * @param label  the label identifying the controlled vocabulary, not {@code null}
	 * @param name  the full name of the controlled vocabulary, not {@code null}
	 * @param uri  the uri specifying the location of the controlled vocabulary, not {@code null}
	 * @param version  the version number of the controlled vocabulary
	 */
	public CV(String label, String name, String uri, String version) {
		this();

		setLabel(label);
		setName(name);
		setUri(uri);
		setVersion(version);
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLabel() {
		return label;
	}

	private void setLabel(String label) {
		if(label != null)
			this.label = label;
		else {
			logger.error("The CV's label is not allowed to be <null>");
			throw new NullPointerException("The CV's label is not allowed to be <null>");
		}
	}

	public String getName() {
		return name;
	}

	private void setName(String name) {
		if(name != null)
			this.name = name;
		else {
			logger.error("The CV's name is not allowed to be <null>");
			throw new NullPointerException("The CV's name is not allowed to be <null>");
		}
	}

	public String getUri() {
		return uri;
	}

	private void setUri(String uri) {
		if(uri != null)
			this.uri = uri;
		else {
			logger.error("The CV's URI is not allowed to be <null>");
			throw new NullPointerException("The CV's URI is not allowed to be <null>");
		}
	}

	public String getVersion() {
		return version;
	}

	private void setVersion(String version) {
		this.version = version;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) return true;
		if(o == null || getClass() != o.getClass()) return false;

		CV cv = (CV) o;

		if(!label.equals(cv.label)) return false;
		if(!name.equals(cv.name)) return false;
		if(!uri.equals(cv.uri)) return false;
		if(version != null ? !version.equals(cv.version) : cv.version != null) return false;

		return true;
	}

	@Override
	public int hashCode() {
		int result = label.hashCode();
		result = 31 * result + name.hashCode();
		result = 31 * result + uri.hashCode();
		result = 31 * result + (version != null ? version.hashCode() : 0);
		return result;
	}

	@Override
	public String toString() {
		return "CV {id=" + id + ", label=" + label + "}";
	}
}
