package inspector.jmondb.model;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.persistence.*;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

/**
 * Represents an event that influenced the mass spectrometer, such as calibrations, maintenance, or unexpected incidents.
 */
@Entity
@Access(AccessType.FIELD)
@Table(name="imon_event")
public class Event {

	@Transient
	private static final Logger logger = LogManager.getLogger(Event.class);

	/** read-only iMonDB primary key; generated by JPA */
	@Id
	@Column(name="id", nullable=false)
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	private Long id;

	/** the {@link Instrument} on which the event occurred */
	@ManyToOne(cascade={CascadeType.PERSIST, CascadeType.MERGE}, fetch=FetchType.EAGER)
	@JoinColumn(name="l_imon_instrument_id", nullable=false, referencedColumnName="id")
	private Instrument instrument;

	/** the date on which the event occurred */
	@Column(name="eventdate", nullable=false)
	private Timestamp date;
	/** the {@link EventType} */
	@Column(name="type", nullable=false)
	private EventType type;
	/** a description of the event */
	@Column(name="description", length=255)
	private String description;

	/** a picture detailing the event */
	@Lob
	@Column(name="picture")
	private byte[] picture;

	/**
	 * Default constructor required by JPA.
	 * Protected access modification enforces (limited) class immutability.
	 */
	protected Event() {

	}

	/**
	 * Creates an {@link Event}.
	 *
	 * @param instrument  the {@link Instrument} on which the event occurred
	 * @param date  the date on which the event occurred
	 * @param type  the {@link EventType}
	 */
	public Event(Instrument instrument, Timestamp date, EventType type) {
		setDate(date);
		setType(type);
		setInstrument(instrument);
	}

	/**
	 * Creates an {@link Event}.
	 *
	 * @param instrument  the {@link Instrument} on which the event occurred
	 * @param date  the date on which the event occurred
	 * @param type  the {@link EventType}
	 * @param description  description of the event
	 */
	public Event(Instrument instrument, Timestamp date, EventType type, String description) {
		this(instrument, date, type);
		setDescription(description);
	}

	/**
	 * Creates an {@link Event}.
	 *
	 * @param instrument  the {@link Instrument} on which the event occurred
	 * @param date  the date on which the event occurred
	 * @param type  the {@link EventType}
	 * @param description  description of the event
	 * @param picture  a picture detailing the event
	 */
	public Event(Instrument instrument, Timestamp date, EventType type, String description, byte[] picture) {
		this(instrument, date, type, description);
		setPicture(picture);
	}

	public Instrument getInstrument() {
		return instrument;
	}

	private void setInstrument(Instrument instrument) {
		if(instrument != null) {
			this.instrument = instrument;
			instrument.addEvent(this);
		}
		else {
			logger.error("The event's instrument is not allowed to be null");
			throw new NullPointerException("The event's instrument is not allowed to be null");
		}
	}

	public Timestamp getDate() {
		return date;
	}

	private void setDate(Timestamp date) {
		if(date != null)
			this.date = date;
		else {
			logger.error("The event's date is not allowed to be null");
			throw new NullPointerException("The event's date is not allowed to be null");
		}
	}

	public EventType getType() {
		return type;
	}

	private void setType(EventType type) {
		if(type != null)
			this.type = type;
		else {
			logger.error("The event's type is not allowed to be null");
			throw new NullPointerException("The event's type is not allowed to be null");
		}
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getPicture() {
		return picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	@Override
	public boolean equals(Object o) {
		if(this == o) return true;
		if(o == null || getClass() != o.getClass()) return false;

		Event event = (Event) o;

		if(!instrument.equals(event.instrument)) return false;
		if(!date.equals(event.date)) return false;
		if(type != event.type) return false;

		return true;
	}

	@Override
	public int hashCode() {
		int result = instrument.hashCode();
		result = 31 * result + date.hashCode();
		result = 31 * result + type.hashCode();
		return result;
	}

	@Override
	public String toString() {
		SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
		return "Event {id=" + id + ", instrument=" + instrument.getName() + ", date=" + sdf.format(date.getTime()) + ", type=" + type.toString() + "}";
	}
}
