package inspector.jmondb.model;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import javax.persistence.*;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

@Entity
@Table(name="imon_project")
public class Project {

	@Transient
	private static final Logger logger = LogManager.getLogger(Project.class);

	/** read-only iMonDB primary key; generated by JPA */
	@Id
	@Column(name="id", nullable=false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;

	/** the project description */
	@Column(name="description", length=255)
	private String description;
	/** the label identifying the project */
	@Column(name="label", nullable=false, unique=true, length=20)
	private String label;
	/** the project title */
	@Column(name="title", nullable=false, length=100)
	private String title;

	/** list of {@link Run}s belonging to the project */
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.EAGER, mappedBy="fromProject")
	@MapKey(name="name")
	private Map<String, Run> hasRuns;

	/**
	 * Default constructor required by JPA.
	 * Protected access modification to enforce that client code uses the constructor that sets the required member variables.
	 */
	protected Project() {
		hasRuns = new HashMap<>();
	}

	/**
	 * Creates a Project with the specified label and title.
	 *
	 * The id is automatically determined by the database as primary key.
	 *
	 * @param label  The label identifying the project
	 * @param title  The project title
	 */
	public Project(String label, String title) {
		this();

		setLabel(label);
		setTitle(title);
	}

	/**
	 * Creates a Project with the specified label, title and description.
	 *
	 *  The primary key is automatically determined by the database.
	 *
	 * @param label  The label identifying the project
	 * @param title  The project title
	 * @param description  The project description
	 */
	public Project(String label, String title, String description) {
		this(label, title);
		setDescription(description);
	}

	public Long getId() {
		return id;
	}

	/* package private: read-only key to be set by the JPA implementation */
	void setId(Long id) {
		this.id = id;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		if(label != null)
			this.label = label;
		else {
			logger.error("The project's label is not allowed to be <null>");
			throw new NullPointerException("The project's label is not allowed to be <null>");
		}
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		if(title != null)
			this.title = title;
		else {
			logger.error("The project's title is not allowed to be <null>");
			throw new NullPointerException("The project's title is not allowed to be <null>");
		}
	}

	/**
	 * Returns the number of {@link Run}s that belong to the project.
	 *
	 * @return The number of Runs that belong to the project
	 */
	public int getNumberOfRuns() {
		return hasRuns.size();
	}

	/**
	 * Returns the {@link Run} with the specified name belonging to the project.
	 *
	 * @param name  The name of the requested Run
	 * @return The Run with the specified name belonging to the project
	 */
	public Run getRun(String name) {
		if(name != null)
			return hasRuns.get(name);
		else
			return null;
	}

	/**
	 * Returns an {@link Iterator} over all {@link Run}s belonging to the project.
	 *
	 * @return An Iterator over all Runs belonging to the project
	 */
	public Iterator<Run> getRunIterator() {
		return hasRuns.values().iterator();
	}

	/**
	 * Adds the given {@link Run} to the project.
	 *
	 * If a Run with the same name was already present, the previous Run is replaced by the given Run.
	 *
	 * @param run  The Run that will be added to the project
	 */
	public void addRun(Run run) {
		if(run != null) {
			run.setFromProject(this);	// add the bi-directional relationship
			hasRuns.put(run.getName(), run);
		}
		else {
			logger.error("Can't add <null> Run to a Project");
			throw new NullPointerException("Can't add <null> Run");
		}
	}

	/**
	 * Removes the {@link Run} specified by the given name from the project.
	 *
	 * @param name  The name of the Run that will be removed
	 */
	public void removeRun(String name) {
		if(name != null) {
			Run run = hasRuns.get(name);
			if(run != null)	// remove the bi-directional relationship
				run.setFromProject(null);
			hasRuns.remove(name);
		}
	}

	/**
	 * Removes all {@link Run}s from the project.
	 */
	public void removeAllRuns() {
		Iterator<Run> it = getRunIterator();
		while(it.hasNext()) {
			Run run = it.next();
			// first remove the bi-directional relationship
			run.setFromProject(null);
			// remove the run
			it.remove();
		}
	}

	/**
	 * Indicates whether some other object is "equal to" this one.
	 *
	 * Two Projects are considered equal if their direct metadata is equal. Possible {@link Run}s in one or both of the Projects are not considered.
	 *
	 * @param o  The reference object with which to compare
	 * @return <code>true</code> if this object is the same as the o argument; <code>false</code> otherwise
	 */
	@Override
	public boolean equals(Object o) {
		if(this == o) return true;
		if(o == null || getClass() != o.getClass()) return false;

		Project that = (Project) o;

		if(id != null ? !id.equals(that.id) : that.id != null) return false;
		if(description != null ? !description.equals(that.description) : that.description != null) return false;
		if(label != null ? !label.equals(that.label) : that.label != null) return false;
		if(title != null ? !title.equals(that.title) : that.title != null) return false;

		return true;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("Project {id=").append(id).append(", label=").append(label).append("\n");
		Iterator<Run> it = getRunIterator();
		while(it.hasNext())
			sb.append("\t").append(it.next()).append("\n");
		sb.append("}");

		return sb.toString();
	}
}
