package inspector.imondb.collector.view.gui.instrument;

/*
 * #%L
 * iMonDB Collector
 * %%
 * Copyright (C) 2014 - 2015 InSPECtor
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import inspector.imondb.collector.model.InstrumentMap;

import javax.swing.*;
import java.awt.*;

public class InstrumentOverviewPanel {

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        panel.setMaximumSize(new Dimension(380, 40));
        panel.setMinimumSize(new Dimension(380, 40));
        panel.setName("");
        panel.setPreferredSize(new Dimension(380, 40));
        buttonEdit = new JButton();
        buttonEdit.setActionCommand("Edit");
        buttonEdit.setHorizontalTextPosition(0);
        buttonEdit.setIcon(new ImageIcon(getClass().getResource("/images/edit.png")));
        buttonEdit.setLabel("");
        buttonEdit.setMaximumSize(new Dimension(29, 29));
        buttonEdit.setMinimumSize(new Dimension(29, 29));
        buttonEdit.setPreferredSize(new Dimension(29, 29));
        buttonEdit.setText("");
        buttonEdit.setToolTipText("Edit the instrument");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panel.add(buttonEdit, gbc);
        buttonRemove = new JButton();
        buttonRemove.setActionCommand("Delete");
        buttonRemove.setHideActionText(true);
        buttonRemove.setHorizontalTextPosition(0);
        buttonRemove.setIcon(new ImageIcon(getClass().getResource("/images/delete.png")));
        buttonRemove.setLabel("");
        buttonRemove.setMaximumSize(new Dimension(29, 29));
        buttonRemove.setMinimumSize(new Dimension(29, 29));
        buttonRemove.setPreferredSize(new Dimension(29, 29));
        buttonRemove.setText("");
        buttonRemove.setToolTipText("Delete the instrument");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panel.add(buttonRemove, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(panel1, gbc);
        labelSource = new JLabel();
        labelSource.setMaximumSize(new Dimension(50, 16));
        labelSource.setMinimumSize(new Dimension(50, 16));
        labelSource.setPreferredSize(new Dimension(50, 16));
        labelSource.setText("source");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(labelSource, gbc);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setHorizontalTextPosition(0);
        label1.setMaximumSize(new Dimension(30, 16));
        label1.setMinimumSize(new Dimension(30, 16));
        label1.setPreferredSize(new Dimension(30, 16));
        label1.setText("->");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        labelRegex = new JLabel();
        labelRegex.setMaximumSize(new Dimension(170, 16));
        labelRegex.setMinimumSize(new Dimension(170, 16));
        labelRegex.setPreferredSize(new Dimension(170, 16));
        labelRegex.setText("regex");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(labelRegex, gbc);
        labelStatus = new JLabel();
        labelStatus.setIcon(new ImageIcon(getClass().getResource("/images/warning.png")));
        labelStatus.setText("");
        labelStatus.setToolTipText("Unverified/new instrument");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(labelStatus, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer3, gbc);
        labelName = new JLabel();
        labelName.setMaximumSize(new Dimension(305, 16));
        labelName.setMinimumSize(new Dimension(305, 16));
        labelName.setPreferredSize(new Dimension(305, 16));
        labelName.setText("Instrument (model)");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel.add(labelName, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    public enum InstrumentStatus {
        VALID, NEW, UNKNOWN, INVALID
    }

    private static ImageIcon iconInvalid = new ImageIcon(InstrumentOverviewPanel.class.getResource("/images/nok.png"));
    private static ImageIcon iconWarning = new ImageIcon(InstrumentOverviewPanel.class.getResource("/images/warning.png"));
    private static ImageIcon iconValid = new ImageIcon(InstrumentOverviewPanel.class.getResource("/images/ok.png"));

    private JPanel panel;

    private JLabel labelName;

    private JLabel labelStatus;
    private JLabel labelSource;
    private JLabel labelRegex;

    private JButton buttonEdit;
    private JButton buttonRemove;

    private InstrumentMap instrumentMap;
    private InstrumentStatus status;

    private InstrumentOverviewPanel(InstrumentsPanel instrumentsPanel) {
        status = InstrumentStatus.UNKNOWN;

        buttonEdit.addActionListener(e -> {
            // edit
            InstrumentCreatePanel instrumentCreatePanel = new InstrumentCreatePanel(instrumentMap);

            int result = JOptionPane.showConfirmDialog(Frame.getFrames()[0], instrumentCreatePanel.getPanel(),
                    "Edit instrument", JOptionPane.OK_CANCEL_OPTION);

            if(result == JOptionPane.OK_OPTION) {
                InstrumentMap instrumentMapNew = instrumentCreatePanel.getInstrumentMap();
                if(instrumentMapNew.isValid()) {
                    setInstrumentMap(instrumentMapNew);
                    instrumentsPanel.editInstrument(instrumentMapNew);
                } else {
                    JOptionPane.showMessageDialog(Frame.getFrames()[0],
                            "<html>Invalid instrument configuration.<br><br>Your changes were undone.</html>",
                            "Error", JOptionPane.WARNING_MESSAGE);
                }
            }
        });

        buttonRemove.addActionListener(e -> {
            instrumentsPanel.removeInstrument(instrumentMap);

            instrumentsPanel.getPanel().revalidate();
            instrumentsPanel.getPanel().repaint();
        });
    }

    public InstrumentOverviewPanel(InstrumentsPanel instrumentsPanel, InstrumentMap instrumentMap) {
        this(instrumentsPanel);

        setInstrumentMap(instrumentMap);
    }

    private void setInstrumentMap(InstrumentMap instrumentMap) {
        this.instrumentMap = instrumentMap;
        labelName.setText(instrumentMap.getKey() + " (" + instrumentMap.getValue().toString() + ")");
        labelSource.setText(instrumentMap.getSource().toString());
        labelRegex.setText(instrumentMap.getRegex());
    }

    public JPanel getPanel() {
        return panel;
    }

    public InstrumentStatus getStatus() {
        return status;
    }

    void setStatus(InstrumentStatus status) {
        this.status = status;

        switch(status) {
            case VALID:
                labelStatus.setIcon(iconValid);
                labelStatus.setToolTipText("Valid instrument");
                break;
            case INVALID:
                labelStatus.setIcon(iconInvalid);
                labelStatus.setToolTipText("Instrument definition conflicting with the database information");
                break;
            case UNKNOWN:
            case NEW:
            default:
                labelStatus.setIcon(iconWarning);
                labelStatus.setToolTipText("Unverified/new instrument");
                break;
        }
    }
}
