sql:
    host: localhost
    port: '3306'
    database: iMonDB
    user:
    password:
general:
    dir:
    last_date:
    match_file: ^.*\.raw$
    force_unique: false
    num_threads: 1
instruments: []
metadata: []
